name: 'Hashnode Blogs'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update_blogs:
    name: 'Hashnode Latest Blogs'
    runs-on: ubuntu-latest
    steps:
      - name: 'Fetch Repository Contents'
        uses: actions/checkout@main

      - name: 'Hashnode Blog Action'
        uses: "Sachin-chaurasiya/hashnode-blog-action@main"
        with:
          HASHNODE_PUBLICATION_NAME: 'lhidalgo.dev'
          FORMAT: 'table'
          POST_COUNT: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
